
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyipqumgopcmmpqhmznp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aXBxdW1nb3BjbW1wcWhtem5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTEwMzgsImV4cCI6MjA1OTA4NzAzOH0.dhTrbAJ2rKng0aAoMKBc9PViVWJ3cTzT9qErFjJPyik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
